// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/voxel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据包类型枚举（对应 Zinx 的 MsgID）
type PacketID int32

const (
	PacketID_LOGIN_REQUEST      PacketID = 0
	PacketID_LOGIN_RESPONSE     PacketID = 1
	PacketID_PLAYER_MOVE        PacketID = 2
	PacketID_PLACE_BLOCK        PacketID = 3
	PacketID_BREAK_BLOCK        PacketID = 4
	PacketID_CHUNK_DATA         PacketID = 5
	PacketID_PLAYER_LIST_UPDATE PacketID = 6
	PacketID_HEARTBEAT          PacketID = 7
)

// Enum value maps for PacketID.
var (
	PacketID_name = map[int32]string{
		0: "LOGIN_REQUEST",
		1: "LOGIN_RESPONSE",
		2: "PLAYER_MOVE",
		3: "PLACE_BLOCK",
		4: "BREAK_BLOCK",
		5: "CHUNK_DATA",
		6: "PLAYER_LIST_UPDATE",
		7: "HEARTBEAT",
	}
	PacketID_value = map[string]int32{
		"LOGIN_REQUEST":      0,
		"LOGIN_RESPONSE":     1,
		"PLAYER_MOVE":        2,
		"PLACE_BLOCK":        3,
		"BREAK_BLOCK":        4,
		"CHUNK_DATA":         5,
		"PLAYER_LIST_UPDATE": 6,
		"HEARTBEAT":          7,
	}
)

func (x PacketID) Enum() *PacketID {
	p := new(PacketID)
	*p = x
	return p
}

func (x PacketID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_voxel_proto_enumTypes[0].Descriptor()
}

func (PacketID) Type() protoreflect.EnumType {
	return &file_proto_voxel_proto_enumTypes[0]
}

func (x PacketID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketID.Descriptor instead.
func (PacketID) EnumDescriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{0}
}

// 基础数据类型
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_proto_voxel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type BlockPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             int32                  `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPosition) Reset() {
	*x = BlockPosition{}
	mi := &file_proto_voxel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPosition) ProtoMessage() {}

func (x *BlockPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPosition.ProtoReflect.Descriptor instead.
func (*BlockPosition) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{1}
}

func (x *BlockPosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BlockPosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BlockPosition) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_voxel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                     // 0=成功，其他=错误码
	PlayerId      uint32                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 服务器分配的玩家ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_voxel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginResponse) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 玩家移动
type PlayerMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      float32                `protobuf:"fixed32,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	mi := &file_proto_voxel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerMove) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerMove) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerMove) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

// 放置方块
type PlaceBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Pos           *BlockPosition         `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	BlockId       uint32                 `protobuf:"varint,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBlock) Reset() {
	*x = PlaceBlock{}
	mi := &file_proto_voxel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBlock) ProtoMessage() {}

func (x *PlaceBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBlock.ProtoReflect.Descriptor instead.
func (*PlaceBlock) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceBlock) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlaceBlock) GetPos() *BlockPosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlaceBlock) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

// 破坏方块
type BreakBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Pos           *BlockPosition         `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakBlock) Reset() {
	*x = BreakBlock{}
	mi := &file_proto_voxel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakBlock) ProtoMessage() {}

func (x *BreakBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakBlock.ProtoReflect.Descriptor instead.
func (*BreakBlock) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{6}
}

func (x *BreakBlock) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *BreakBlock) GetPos() *BlockPosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 区块数据
type ChunkData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChunkX           int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkZ           int32                  `protobuf:"varint,2,opt,name=chunk_z,json=chunkZ,proto3" json:"chunk_z,omitempty"`
	CompressedBlocks []byte                 `protobuf:"bytes,3,opt,name=compressed_blocks,json=compressedBlocks,proto3" json:"compressed_blocks,omitempty"` // zstd压缩后的方块数据
	EntityIds        []uint64               `protobuf:"varint,4,rep,packed,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`              // 区块内实体ID列表
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_proto_voxel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkData) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *ChunkData) GetChunkZ() int32 {
	if x != nil {
		return x.ChunkZ
	}
	return 0
}

func (x *ChunkData) GetCompressedBlocks() []byte {
	if x != nil {
		return x.CompressedBlocks
	}
	return nil
}

func (x *ChunkData) GetEntityIds() []uint64 {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

// 玩家列表更新
type PlayerListUpdate struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Players       []*PlayerListUpdate_PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerListUpdate) Reset() {
	*x = PlayerListUpdate{}
	mi := &file_proto_voxel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerListUpdate) ProtoMessage() {}

func (x *PlayerListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerListUpdate.ProtoReflect.Descriptor instead.
func (*PlayerListUpdate) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerListUpdate) GetPlayers() []*PlayerListUpdate_PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// 心跳（空消息）
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_voxel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{9}
}

type PlayerListUpdate_PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerListUpdate_PlayerInfo) Reset() {
	*x = PlayerListUpdate_PlayerInfo{}
	mi := &file_proto_voxel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerListUpdate_PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerListUpdate_PlayerInfo) ProtoMessage() {}

func (x *PlayerListUpdate_PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voxel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerListUpdate_PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerListUpdate_PlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_voxel_proto_rawDescGZIP(), []int{8, 0}
}

func (x *PlayerListUpdate_PlayerInfo) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerListUpdate_PlayerInfo) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_proto_voxel_proto protoreflect.FileDescriptor

const file_proto_voxel_proto_rawDesc = "" +
	"\n" +
	"\x11proto/voxel.proto\x12\x05voxel\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"9\n" +
	"\rBlockPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x05R\x01z\"/\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"D\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\rR\bplayerId\"q\n" +
	"\n" +
	"PlayerMove\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12*\n" +
	"\bposition\x18\x02 \x01(\v2\x0e.voxel.Vector3R\bposition\x12\x1a\n" +
	"\brotation\x18\x03 \x01(\x02R\brotation\"l\n" +
	"\n" +
	"PlaceBlock\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12&\n" +
	"\x03pos\x18\x02 \x01(\v2\x14.voxel.BlockPositionR\x03pos\x12\x19\n" +
	"\bblock_id\x18\x03 \x01(\rR\ablockId\"Q\n" +
	"\n" +
	"BreakBlock\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12&\n" +
	"\x03pos\x18\x02 \x01(\v2\x14.voxel.BlockPositionR\x03pos\"\x89\x01\n" +
	"\tChunkData\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_z\x18\x02 \x01(\x05R\x06chunkZ\x12+\n" +
	"\x11compressed_blocks\x18\x03 \x01(\fR\x10compressedBlocks\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x04 \x03(\x04R\tentityIds\"\xa7\x01\n" +
	"\x10PlayerListUpdate\x12<\n" +
	"\aplayers\x18\x01 \x03(\v2\".voxel.PlayerListUpdate.PlayerInfoR\aplayers\x1aU\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12*\n" +
	"\bposition\x18\x02 \x01(\v2\x0e.voxel.Vector3R\bposition\"\v\n" +
	"\tHeartbeat*\x9b\x01\n" +
	"\bPacketID\x12\x11\n" +
	"\rLOGIN_REQUEST\x10\x00\x12\x12\n" +
	"\x0eLOGIN_RESPONSE\x10\x01\x12\x0f\n" +
	"\vPLAYER_MOVE\x10\x02\x12\x0f\n" +
	"\vPLACE_BLOCK\x10\x03\x12\x0f\n" +
	"\vBREAK_BLOCK\x10\x04\x12\x0e\n" +
	"\n" +
	"CHUNK_DATA\x10\x05\x12\x16\n" +
	"\x12PLAYER_LIST_UPDATE\x10\x06\x12\r\n" +
	"\tHEARTBEAT\x10\aB\x15Z\x13voxel-backend/protob\x06proto3"

var (
	file_proto_voxel_proto_rawDescOnce sync.Once
	file_proto_voxel_proto_rawDescData []byte
)

func file_proto_voxel_proto_rawDescGZIP() []byte {
	file_proto_voxel_proto_rawDescOnce.Do(func() {
		file_proto_voxel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_voxel_proto_rawDesc), len(file_proto_voxel_proto_rawDesc)))
	})
	return file_proto_voxel_proto_rawDescData
}

var file_proto_voxel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_voxel_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_voxel_proto_goTypes = []any{
	(PacketID)(0),                       // 0: voxel.PacketID
	(*Vector3)(nil),                     // 1: voxel.Vector3
	(*BlockPosition)(nil),               // 2: voxel.BlockPosition
	(*LoginRequest)(nil),                // 3: voxel.LoginRequest
	(*LoginResponse)(nil),               // 4: voxel.LoginResponse
	(*PlayerMove)(nil),                  // 5: voxel.PlayerMove
	(*PlaceBlock)(nil),                  // 6: voxel.PlaceBlock
	(*BreakBlock)(nil),                  // 7: voxel.BreakBlock
	(*ChunkData)(nil),                   // 8: voxel.ChunkData
	(*PlayerListUpdate)(nil),            // 9: voxel.PlayerListUpdate
	(*Heartbeat)(nil),                   // 10: voxel.Heartbeat
	(*PlayerListUpdate_PlayerInfo)(nil), // 11: voxel.PlayerListUpdate.PlayerInfo
}
var file_proto_voxel_proto_depIdxs = []int32{
	1,  // 0: voxel.PlayerMove.position:type_name -> voxel.Vector3
	2,  // 1: voxel.PlaceBlock.pos:type_name -> voxel.BlockPosition
	2,  // 2: voxel.BreakBlock.pos:type_name -> voxel.BlockPosition
	11, // 3: voxel.PlayerListUpdate.players:type_name -> voxel.PlayerListUpdate.PlayerInfo
	1,  // 4: voxel.PlayerListUpdate.PlayerInfo.position:type_name -> voxel.Vector3
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_voxel_proto_init() }
func file_proto_voxel_proto_init() {
	if File_proto_voxel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_voxel_proto_rawDesc), len(file_proto_voxel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_voxel_proto_goTypes,
		DependencyIndexes: file_proto_voxel_proto_depIdxs,
		EnumInfos:         file_proto_voxel_proto_enumTypes,
		MessageInfos:      file_proto_voxel_proto_msgTypes,
	}.Build()
	File_proto_voxel_proto = out.File
	file_proto_voxel_proto_goTypes = nil
	file_proto_voxel_proto_depIdxs = nil
}
